### ISSUE TITLE
is this 1.5 Bit implementation ?

### ISSUE THREAD

**Issue by JAYANTH-MOHAN** [areddy2022/1.58bits#1]
I see the weights are being clipped but isn't it still in the same datatype (standard 32-bit floating-point data type)?

**Comment by areddy2022** [comment]
Hi Jayanth,

That is correct. The original paper was using Ladder to generate a custom 2 bit kernel. In this way, they were able to measure performance. We are currently working on generating a custom kernel, and then implementing true 1.58 built weights in the weight matrix. We hope to have it finished by the end of the week.

**Comment by JAYANTH-MOHAN** [comment]
Thanks
